name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: lint
        run: |
          cd rust_cli
          rustup component add clippy
          cargo clippy -- -D warnings

      - name: test
        run:
          cd rust_cli
          cargo test

      - name: Build Rust project
        run: |
          cd rust_cli
          cargo build --release


